return {
	settings = {
		gopls = {
			codelenses = {
				generate = true,
				gc_details = true,
				test = true,
				tidy = true,
				vendor = true,
				regenerate_cgo = false,
				upgrade_dependency = true,
				run_govulncheck = true,
			},
			hints = {
				assignVariableTypes = true,
				compositeLiteralFields = true,
				compositeLiteralTypes = true,
				constantValues = true,
				functionTypeParameters = true,
				parameterNames = true,
				rangeVariableTypes = true,
			},
			analyses = {
				nilness = true,
				unusedparams = true,
				unusedwrite = true,
				ST1003 = true,
				undeclaredname = true,
				fillreturns = true,
				nonewvars = true,
				useany = true,
				unreachable = true,
				unusedresult = true,
				simplifyslice = true,
				simplifyrange = true,
				simplifycompositelit = true,
				shadow = false,
				printf = true,
				structtag = true,
				modernize = true,
				stylecheck = true,
				gocritic = true,
				deprecated = true,
			},
			usePlaceholders = true,
			completeUnimported = true,
			staticcheck = true,
			matcher = "Fuzzy",
			diagnosticsDelay = "500ms",
			symbolMatcher = "fuzzy",
			directoryFilters = {
				"-.git",
				"-.vscode",
				"-.idea",
				"-.vscode-test",
				"-node_modules",
			},
			semanticTokens = true,
			gofumpt = true,
		},
	},
}
